### ISSUE TITLE
关于企鹅物流wiki识别图片出现问题

### ISSUE THREAD

**Issue by ARK-Prisoner** [KumoSiunaus/penguin#2]
这是我上传的两张图片
![360截图1622042297133114](https://user-images.githubusercontent.com/98634285/151649697-db408027-f797-43b1-8292-47a53ff6c49e.png)
![360截图1663050798131107](https://user-images.githubusercontent.com/98634285/151649708-8e8a7d68-c840-4ddb-8e14-45205de7febb.png)
这是识别的结果
![image](https://user-images.githubusercontent.com/98634285/151649729-f4ff9d6f-e2e3-4f32-89a8-761bc1dafd20.png)
麻烦您看看是什么问题？

**Comment by KumoSiunaus** [comment]
您好，经过检测排查，您的图片分辨率过低导致识别过程出现了问题。
您可以考虑提高模拟器的分辨率，或考虑使用模拟器的内置截图功能。
我们也会就此问题继续提升我们的识别精度。

感谢您对企鹅物流数据统计的支持。

2022年1月29日(土) 14:04 ARK-Prisoner ***@***.***>:
